const callbacks = [
  'viewRender',
  'viewDestroy',
  'dayRender',
  'windowResize',
  'navLinkDayClick',
  'navLinkWeekClick',
  'dayClick',
  'eventClick',
  'eventMouseover',
  'eventMouseout',
  'select',
  'unselect',
  'eventDataTransform',
  'loading',
  'eventRender',
  'eventAfterRender',
  'eventAfterAllRender',
  'eventDestroy',
  'eventDragStart',
  'eventDragStop',
  'eventDrop',
  'eventResizeStart',
  'eventResizeStop',
  'eventResize',
  'drop',
  'eventReceive',
  'dayClick',
  'loading',
  'resourceText',
  'resourceRender',
];


const methods = [
  'render',
  'destroy',
  'getView',
  'changeView',
  'prev',
  'next',
  'prevYear',
  'nextYear',
  'today',
  'gotoDate',
  'incrementDate',
  'getDate',
  'select',
  'unselect',
  'updateEvent',
  'updateEvents',
  'clientEvents',
  'removeEvents',
  'refetchEvents',
  'refetchEventSources',
  'addEventSource',
  'removeEventSource',
  'removeEventSources',
  'getEventSources',
  'getEventSourceById',
  'renderEvent',
  'renderEvents',
  'rerenderEvents',
  'getResources',
  'getResourceById',
  'getResourceEvents',
  'getEventResource',
  'addResource',
  'removeResource',
  'refetchResources',
];

const notCallback = item => callbacks.indexOf(item) === -1;
const notMethod = item => methods.indexOf(item) === -1;

const isCallback = callbackName => !notCallback(callbackName);
const isMethod = methodName => !notMethod(methodName);
const isOption = optionName => notCallback(optionName) && notMethod(optionName);

export { isCallback, isMethod, isOption };
